export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
export { default as Main } from "./Main";
export { default as ProductList } from "./ProductList";
export { default as Product } from "./Product";
export { default as Error } from "./Error";
export { default as Cart } from "./Cart";
export { default as Blog } from "./Blog";
export { default as Order } from "./Order";
